### ISSUE TITLE
Who knows where these files are?I cant find these

### ISSUE THREAD

**Issue by SKJKC** [cvlab-stonybrook/BodyHands#2]
![image](https://user-images.githubusercontent.com/49215575/178285325-036a2369-514e-4ba1-a3f5-6cfefc882119.png)
![image](https://user-images.githubusercontent.com/49215575/178285524-96961475-f2fc-40ab-b60d-8e8f5f064f80.png)

**Comment by SupreethN** [comment]
Thanks for your interest in our work. Check out `__init__.py` files in individual subdirectories to see which python files they are imported from.
