### ISSUE TITLE
Error on git clone BodyHands_private

### ISSUE THREAD

**Issue by anjugopinath** [cvlab-stonybrook/BodyHands#3]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/4654298/194232164-f5c3bf5c-0043-419f-b62c-f826ebf02c4e.png">

**Comment by SupreethN** [comment]
Thanks for your interest in our work. I hope you could clone the repository successfully. If not, please download the repository as a zip file.

**Comment by MichaelGMoore** [comment]
I have the same issue, and cannot find this repository in order to download as zip file.
